name = "han-analytics"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-21"

[[analytics_engine_datasets]]
binding = "AnalyticsBinding"
dataset = "AnalyticsDataset"
[vars]
CLOUDFLARE_ACCOUNT_ID = 'de8f73ed9a9cba189ae685a6602d2755'
CLOUDFLARE_API_TOKEN = 'DAia_J2lUfxtfpZqo66LEnrRJ9_uJDDUkTSou3Rj'
